modules/meeting/config/routes.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

OpenProject::Application.routes.draw do
  resources :projects, only: %i[] do
    resources :meetings, only: %i[index new create]
  end

  resources :meetings do
    resource :agenda, controller: 'meeting_agendas', only: [:update] do
      member do
        get :history
        get :diff
        put :close
        put :open
        put :notify
        put :icalendar
        post :preview
      end

      resources :versions, only: [:show],
                           controller: 'meeting_agendas'
    end

    resource :contents, controller: 'meeting_contents', only: %i[show update] do
      member do
        get :history
        get :diff
        put :notify
        get :icalendar
      end
    end

    resource :minutes, controller: 'meeting_minutes', only: [:update] do
      member do
        get :history
        get :diff
        put :notify
        post :preview
      end

      resources :versions, only: [:show],
                           controller: 'meeting_minutes'
    end

    member do
      get :copy
      match '/:tab' => 'meetings#show', :constraints => { tab: /(agenda|minutes)/ },
            :via => :get,
            :as => 'tab'
    end
  end
end

modules/meeting/app/models/queries/meetings.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

module Queries::Meetings
  ::Queries::Register.register(MeetingQuery) do
    filter Filters::ProjectFilter
    filter Filters::TimeFilter
    filter Filters::AttendedUserFilter
    filter Filters::InvitedUserFilter
    filter Filters::AuthorFilter
  end
end

modules/meeting/app/models/queries/meetings/filters/attended_user_filter.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class Queries::Meetings::Filters::AttendedUserFilter < Queries::Meetings::Filters::MeetingFilter
  def type
    :list_optional
  end

  def type_strategy
    # Instead of getting the IDs of all the projects a user is allowed
    # to see we only check that the value is an integer.  Non valid ids
    # will then simply create an empty result but will not cause any
    # harm.
    @type_strategy ||= ::Queries::Filters::Strategies::IntegerListOptional.new(self)
  end

  def where
    "meeting_participants.user_id IN (#{values.join(',')}) AND meeting_participants.attended"
  end

  def scope
    super.joins(:participants)
  end

  def self.key
    :attended_user_id
  end

  def available_operators
    [::Queries::Operators::Equals]
  end
end

modules/meeting/app/controllers/meetings_controller.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class MeetingsController < ApplicationController
  around_action :set_time_zone
  before_action :find_optional_project, only: %i[index new create]
  before_action :build_meeting, only: %i[new create]
  before_action :find_meeting, except: %i[index new create]
  before_action :convert_params, only: %i[create update]
  before_action :authorize, except: %i[index new]
  before_action :authorize_global, only: %i[index new]

  helper :watchers
  helper :meeting_contents
  include MeetingsHelper
  include Layout
  include WatchersHelper
  include PaginationHelper
  include SortHelper

  menu_item :new_meeting, only: %i[new create]

  def index
    @query = load_query
    @meetings = load_meetings(@query)
    render 'index', locals: { menu_name: project_or_global_menu }
  end

  current_menu_item :index do
    :meetings
  end

  def show
    params[:tab] ||= 'minutes' if @meeting.agenda.present? && @meeting.agenda.locked?
  end

  def create
    @meeting.participants.clear # Start with a clean set of participants
    @meeting.participants_attributes = @converted_params.delete(:participants_attributes)
    @meeting.attributes = @converted_params
    if params[:copied_from_meeting_id].present? && params[:copied_meeting_agenda_text].present?
      @meeting.agenda = MeetingAgenda.new(
        text: params[:copied_meeting_agenda_text],
        journal_notes: I18n.t('meeting.copied', id: params[:copied_from_meeting_id])
      )
      @meeting.agenda.author = User.current
    end
    if @meeting.save
      text = I18n.t(:notice_successful_create)
      if User.current.time_zone.nil?
        link = I18n.t(:notice_timezone_missing, zone: Time.zone)
        text += " #{view_context.link_to(link, { controller: '/my', action: :account }, class: 'link_to_profile')}"
      end
      flash[:notice] = text.html_safe

      redirect_to action: 'show', id: @meeting
    else
      render template: 'meetings/new', project_id: @project
    end
  end

  def new; end

  current_menu_item :new do
    :meetings
  end

  def copy
    params[:copied_from_meeting_id] = @meeting.id
    params[:copied_meeting_agenda_text] = @meeting.agenda.text if @meeting.agenda.present?
    @meeting = @meeting.copy(author: User.current)
    render action: 'new', project_id: @project
  end

  def destroy
    @meeting.destroy
    flash[:notice] = I18n.t(:notice_successful_delete)
    redirect_to action: 'index', project_id: @project
  end

  def edit; end

  def update
    @meeting.participants_attributes = @converted_params.delete(:participants_attributes)
    @meeting.attributes = @converted_params
    if @meeting.save
      flash[:notice] = I18n.t(:notice_successful_update)
      redirect_to action: 'show', id: @meeting
    else
      render action: 'edit'
    end
  end

  private

  def load_query
    query = ParamsToQueryService.new(
      Meeting,
      current_user
    ).call(params)

    query = apply_default_filter_if_none_given(query)

    if @project
      query.where("project_id", '=', @project.id)
    end

    query
  end

  def apply_default_filter_if_none_given(query)
    return query if query.filters.any?

    query.where("time", "=", Queries::Meetings::Filters::TimeFilter::FUTURE_VALUE)
  end

  def load_meetings(query)
    query
      .results
      .paginate(page: page_param, per_page: per_page_param)
  end

  def set_time_zone(&)
    zone = User.current.time_zone
    if zone.nil?
      localzone = Time.current.utc_offset
      localzone -= 3600 if Time.current.dst?
      zone = ::ActiveSupport::TimeZone[localzone]
    end

    Time.use_zone(zone, &)
  end

  def build_meeting
    @meeting = Meeting.new
    @meeting.project = @project
    @meeting.author = User.current
  end

  def global_upcoming_meetings
    projects = Project.allowed_to(User.current, :view_meetings)

    Meeting.where(project: projects).from_today
  end

  def find_meeting
    @meeting = Meeting
               .includes([:project, :author, { participants: :user }, :agenda, :minutes])
               .find(params[:id])
    @project = @meeting.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def convert_params
    # We do some preprocessing of `meeting_params` that we will store in this
    # instance variable.
    @converted_params = meeting_params.to_h

    @converted_params[:duration] = @converted_params[:duration].to_hours
    # Force defaults on participants
    @converted_params[:participants_attributes] ||= {}
    @converted_params[:participants_attributes].each { |p| p.reverse_merge! attended: false, invited: false }
  end

  def meeting_params
    if params[:meeting].present?
      params.require(:meeting).permit(:title, :location, :start_time,
                                      :duration, :start_date, :start_time_hour,
                                      participants_attributes: %i[email name invited attended user user_id meeting id])
    end
  end
end

modules/meeting/app/helpers/meetings_helper.rb
#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2023 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

module MeetingsHelper
  def top_level_sidebar_menu_items
    [
      menu_upcoming_meetings_item,
      menu_past_meetings_item
    ]
  end

  def involvement_sidebar_menu_items
    [
      menu_upcoming_invitations_item,
      menu_past_invitations_item,
      menu_attendee_item,
      menu_creator_item
    ]
  end

  def menu_upcoming_meetings_item
    path = project_or_global_meetings_path

    menu_link_element path, t(:label_upcoming_meetings)
  end

  def menu_past_meetings_item
    path = project_or_global_meetings_path(
      filters: [{ time: { operator: '=', values: ['past'] } }],
      sort: 'start_time:desc'
    )

    menu_link_element path, t(:label_past_meetings)
  end

  def menu_upcoming_invitations_item
    path = project_or_global_meetings_path(
      filters: [
        { time: { operator: '=', values: ['future'] } },
        { invited_user_id: { operator: '=', values: [User.current.id.to_s] } }
      ],
      sort: 'start_time'
    )

    menu_link_element path, t(:label_upcoming_invitations)
  end

  def menu_past_invitations_item
    path = project_or_global_meetings_path(
      filters: [
        { time: { operator: '=', values: ['past'] } },
        { invited_user_id: { operator: '=', values: [User.current.id.to_s] } }
      ],
      sort: 'start_time:desc'
    )

    menu_link_element path, t(:label_past_invitations)
  end

  def menu_attendee_item
    path = project_or_global_meetings_path(
      filters: [{ attended_user_id: { operator: '=', values: [User.current.id.to_s] } }]
    )

    menu_link_element path, t(:label_attendee)
  end

  def menu_creator_item
    path = project_or_global_meetings_path(
      filters: [{ author_id: { operator: '=', values: [User.current.id.to_s] } }]
    )

    menu_link_element path, t(:label_author)
  end

  def project_or_global_meetings_path(filters: nil, sort: nil)
    return polymorphic_path([@project, :meetings]) if filters.blank? && sort.blank?

    query_params = {}.tap do |query|
      query[:filters] = filters.to_json if filters.present?
      query[:sort] = sort if sort.present?
    end

    polymorphic_path([@project, :meetings], query_params)
  end

  def menu_link_element(path, label)
    link_to path, class: menu_item_css_class(path), title: label do
      content_tag(:span, class: 'op-sidemenu--item-title') do
        label
      end
    end
  end

  def menu_item_css_class(path)
    "op-sidemenu--item-action#{menu_item_selected(path) ? ' selected' : ''}"
  end

  def menu_item_selected(menu_item_path)
    menu_item_path == request.fullpath
  end

  def format_participant_list(participants)
    if participants.any?
      user_links = participants
        .sort
        .reject { |p| p.user.nil? }
        .map { |p| link_to_user p.user }

      safe_join(user_links, '; ')
    else
      t('placeholders.default')
    end
  end

  def render_meeting_journal(model, journal, options = {})
    return '' if journal.initial?

    journal_content = render_journal_details(journal, :label_updated_time_by, model, options)
    content_tag 'div', journal_content,  id: "change-#{journal.id}", class: 'journal'
  end

  # This renders a journal entry with a header and details
  def render_journal_details(journal, header_label = :label_updated_time_by, _model = nil, options = {})
    header = <<-HTML
      <div class="profile-wrap">
        #{avatar(journal.user)}
      </div>
      <h4>
        <div class="journal-link" style="float:right;">#{link_to "##{journal.anchor}", anchor: "note-#{journal.anchor}"}</div>
        #{authoring journal.created_at, journal.user, label: header_label}
        #{content_tag('a', '', name: "note-#{journal.anchor}")}
      </h4>
    HTML

    if journal.details.any?
      details = content_tag 'ul', class: 'details journal-attributes' do
        journal.details.map do |detail|
          if d = journal.render_detail(detail, cache: options[:cache])
            content_tag('li', d.html_safe)
          end
        end.compact.join(' ').html_safe
      end
    end

    content_tag('div', "#{header}#{details}".html_safe, id: "change-#{journal.id}", class: 'journal')
  end

  def global_create_context?
    request.path == new_meeting_path
  end
end

modules/meeting/app/views/meetings/_form.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2023 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<%= error_messages_for 'meeting' %>

<section class="form--section">

  <div class="form--field -required">
    <%= f.text_field :title, :required => true, :size => 60, container_class: '-wide' %>
  </div>

  <% if global_create_context? %>
    <div class="form--field -required">
      <label class="form--label" for="project_id"><%= Meeting.human_attribute_name(:project) %>:</label>
      <div class="form--field-container">
        <%= angular_component_tag 'op-project-autocompleter',
                                  inputs: {
                                    apiFilters: [['user_action', '=', ['meetings/create']]],
                                    name: 'project_id',
                                    value: @project,
                                    appendTo: 'body',
                                    hiddenFieldAction: 'change->refresh-on-form-changes#triggerTurboStream',
                                  },
                                  id: 'project_id',
                                  class: 'form--select-container -wide remote-field--input',
                                  data: {
                                    'qa-selector': 'project_id'
                                  }
        %>
      </div>
    </div>
  <% end %>

  <div class="form--field">
    <%= f.text_field :location, :size => 60, container_class: '-wide' %>
  </div>

  <div class="form--field -required">
    <label for="meeting_start_date" class="form--label"><%= Meeting.human_attribute_name(:start_date) %>
      <span class="hidden-for-sighted">
        <%= t(:label_start_date)%><%= t(:text_hint_date_format) %>
      </span>
    </label>

    <div class="form--field-container -visible-overflow">
      <%= f.date_picker :start_date,
                        id: 'meeting-form-start-date',
                        required: true,
                        no_label: true
      %>
      <label for="meeting-form-start-time" class="hidden-for-sighted">
        <%= Meeting.human_attribute_name(:start_time) %>
        <label lang="en">
          <%= t(:label_time_zone) %>
          <%= Time.zone.to_s %>
        </label>
      </label>
      <%= f.text_field :start_time_hour,
            id: 'meeting-form-start-time',
            required: true,
            type:     'time',
            no_label: true,
            step:     5.minutes,
            suffix:   Time.zone.to_s,
            container_class: '-xslim' %>
    </div>
  </div>

  <div class="form--field -required">
    <label for="meeting-form-duration" class="form--label"><%= Meeting.human_attribute_name(:duration) %></label>
    <div class="form--field-container">
      <%= f.number_field :duration,
            id: 'meeting-form-duration',
            required: true,
            size:     5,
            no_label: true,
            min:      0.00,
            step:     0.25,
            max:      168,
            suffix:   t(:text_in_hours),
            container_class: '-xslim' %>
    </div>
  </div>

  <%= render partial: 'meetings/participants_section' %>

  <%= hidden_field_tag "copied_from_meeting_id", params[:copied_from_meeting_id] if params[:copied_from_meeting_id].present? %>
  <%= hidden_field_tag "copied_meeting_agenda_text", params[:copied_meeting_agenda_text] if params[:copied_meeting_agenda_text].present? %>
</section>

modules/meeting/app/views/meetings/_menu_query_select.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2023 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<div class="op-sidebar">
  <div class="op-sidebar--body">
    <div class="op-sidemenu">
      <ul class="op-sidemenu--items">
        <% top_level_sidebar_menu_items.each do |menu_item| %>
          <li class="op-sidemenu--item">
            <%= menu_item %>
          </li>
        <% end %>
      </ul>

      <div class="op-sidemenu"
           data-controller="menus--expandable-sidemenu"
           data-application-target="dynamic">

        <button class="op-sidemenu--title"
                type="button"
                data-action="click->menus--expandable-sidemenu#toggleContainer">
          <span class="icon3 icon-small icon-arrow-up1"
                aria-hidden="true"
                data-menus--expandable-sidemenu-target="indicator">
          </span>
          <%= t(:label_involvement) %>
        </button>

        <ul class="op-sidemenu--items"
            data-menus--expandable-sidemenu-target="container">
          <% involvement_sidebar_menu_items.each do |menu_item| %>
            <li class="op-sidemenu--item">
              <%= menu_item %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="op-sidebar--footer">
    <% if User.current.allowed_to?(:create_meetings, @project, global: true) %>
      <%= button_to polymorphic_path([:new, @project, :meeting]),
                    { method: :get,
                      class: 'button -alt-highlight -expand',
                      aria: { label: t(:label_meeting_new) },
                      title: t(:label_meeting_new) } do %>
        <%= spot_icon('add') %>
        <span><%= Meeting.model_name.human %></span>
      <% end %>
    <% end %>
  </div>
</div>

modules/meeting/app/views/meetings/show.html.erb
<%#-- copyright
OpenProject is an open source project management software.
Copyright (C) 2012-2023 the OpenProject GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See COPYRIGHT and LICENSE files for more details.

++#%>

<% html_title "#{t(:label_meeting)}: #{@meeting.title}" %>
<%= toolbar title: t(:label_meeting),
            link_to: link_to(@meeting),
            html: { class: 'meeting--main-toolbar' } do %>
  <% unless User.current.anonymous? %>
    <li class="toolbar-item hidden-for-mobile">
      <div class="button">
        <%= watcher_link @meeting, User.current %>
      </div>
    </li>
  <% end %>
  <% if authorize_for(:meetings, :edit) %>
    <li class="toolbar-item">
      <%= link_to({:controller => '/meetings', :action => 'edit', :id => @meeting}, class: 'button',:accesskey => accesskey(:edit)) do%>
        <%= op_icon('button--icon icon-edit') %>
        <span class="button--text"><%= t(:button_edit) %></span>
      <% end %>
    </li>
  <% end %>
  <% if authorize_for(:meetings, :copy) %>
    <li class="toolbar-item hidden-for-mobile">
      <%= link_to({:controller => '/meetings', :action => 'copy', :id => @meeting}, class: 'button') do %>
        <%= op_icon('button--icon icon-copy') %>
        <span class="button--text"><%= t(:button_copy) %></span>
      <% end %>
    </li>
  <% end %>
  <% if authorize_for(:meetings, :destroy) %>
    <li class="toolbar-item">
      <%= link_to({controller: '/meetings', action: 'destroy', id: @meeting},
                  class: 'button',
                  method: :delete,
                  data: { confirm: t(:text_are_you_sure) }) do %>
        <%= op_icon('button--icon icon-delete') %>
        <span class="button--text"><%= t(:button_delete) %></span>
      <% end %>
    </li>
  <% end %>
<% end %>

<div class="meeting details box">
  <div class="grid-block wrap">
    <div class="grid-content small-12 block--author">
      <%= avatar(@meeting.author) %>
      <p class="author"><%= authoring @meeting.created_at, @meeting.author %></p>
    </div>
    <div class="grid-content small-6">
      <p><strong><%= Meeting.human_attribute_name(:start_time) %></strong>: <%= format_date @meeting.start_time %> <%= format_time @meeting.start_time, false %> - <%= format_time @meeting.end_time, false %> <%= Time.zone %></p>
    </div>
    <div class="grid-content small-6">
      <p><strong><%= Meeting.human_attribute_name(:location) %></strong>: <%=h @meeting.location %></p>
    </div>
    <div class="grid-content small-12">
      <p><strong><%= Meeting.human_attribute_name(:participants_invited) %></strong>: <%= format_participant_list @meeting.participants.invited %></p>
    </div>
    <div class="grid-content small-12">
      <p><strong><%= Meeting.human_attribute_name(:participants_attended) %></strong>: <%= format_participant_list @meeting.participants.attended %></p>
    </div>
  </div>
</div>

<%= render_tabs [{:name => 'agenda', :action => :create_meeting_agendas, :partial => 'meeting_contents/show', :path => meeting_agenda_path(@meeting), :label => :label_meeting_agenda, :content => @meeting.agenda || @meeting.build_agenda, :content_type => "meeting_agenda"},
                 {:name => 'minutes', :action => :create_meeting_minutes, :partial => 'meeting_contents/show', :path => meeting_minutes_path(@meeting), :label => :label_meeting_minutes, :content => @meeting.minutes || @meeting.build_minutes, :content_type => "meeting_minutes"}] %>

<% if @meeting.journals.changing.present? %>
<div id="history">
  <h3><%=t(:label_history)%></h3>
  <% @meeting.journals.each do |journal| %>
    <%= render_meeting_journal @meeting, journal %>
  <% end %>
</div>
<% end %>